### ISSUE TITLE
只支持基础库 v2.9.0 以上，太高了点呀。。

### ISSUE THREAD

**Issue by clevok** [yangmingshan/vue-mini#3]

**Comment by yangmingshan** [comment]
根据微信的[基础库版本分布](https://developers.weixin.qq.com/miniprogram/dev/framework/client-lib/version.html)数据，基础库 v2.9.0 及以上已经覆盖了 96.44% 的用户。

要兼容基础库 v2.9.0 以下的话，需要写一些兼容代码。

考虑到 vue-mini 目前还出于 beta 版本，正式发布时基础库 v2.9.0 及以上的覆盖率会更高。

综上考虑，我认为只支持基础库 v2.9.0 及以上是个合理的选择。
